on:
  push:
    paths:
      - R/scrape_projects.R
      - R/shapeyourcity.R
      - .github/workflows/shapeyourcity_scrape.yaml
  schedule:
    - cron: "35 0,12 * * *"

name: Scrape CoV projects

jobs:
  render:
    name: Scrape CoV projects
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      nextzen_API_key: ${{ secrets.NEXTZEN_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and required packages
        run: |
          install.packages("dplyr")
          install.packages("readr")
          install.packages("here")
          install.packages("rvest")
          install.packages("jsonlite")
          install.packages("httr")
        shell: Rscript {0}
      - name: Scrape projects
        run: |
          srouce('R/scrape_projects.R')
        shell: Rscript {0} 
     - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'data/shapeyourcity.csv' || echo "No changes to commit"
          git push origin || echo "No changes to commit"